# Generated by Django 3.2.6 on 2021-08-27 01:35

from django.db import migrations, models
import django.db.models.deletion
import guacamole.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guacamole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuacamoleConnection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=128)),
                ('protocol', models.CharField(default='rdp', max_length=32)),
                ('proxy_port', models.IntegerField(blank=True, null=True)),
                ('proxy_hostname', models.CharField(blank=True, max_length=512, null=True)),
                ('proxy_encryption_method', models.CharField(blank=True, max_length=4, null=True)),
                ('max_connections', models.IntegerField(blank=True, null=True)),
                ('max_connections_per_user', models.IntegerField(blank=True, null=True)),
                ('connection_weight', models.IntegerField(blank=True, null=True)),
                ('failover_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'guacamole_connection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionGroup',
            fields=[
                ('connection_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_group_name', models.CharField(max_length=128)),
                ('type', guacamole.fields.GuacamoleConnectionGroupTypeField(choices=[('ORGANIZATIONAL', 'ORGANIZATIONAL'), ('BALANCING', 'BALANCING')], default='ORGANIZATIONAL')),
                ('max_connections', models.IntegerField(blank=True, null=True)),
                ('max_connections_per_user', models.IntegerField(blank=True, null=True)),
                ('enable_session_affinity', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'guacamole_connection_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('remote_host', models.CharField(blank=True, max_length=256, null=True)),
                ('connection_name', models.CharField(max_length=128)),
                ('sharing_profile_name', models.CharField(blank=True, max_length=128, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guacamole_connection_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleEntity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'guacamole_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleSharingProfile',
            fields=[
                ('sharing_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('sharing_profile_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'guacamole_sharing_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=32)),
                ('password_salt', models.CharField(blank=True, max_length=32, null=True)),
                ('password_date', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('access_window_start', models.TimeField(blank=True, null=True)),
                ('access_window_end', models.TimeField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email_address', models.CharField(blank=True, max_length=256, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('organizational_role', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'guacamole_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserGroup',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'guacamole_user_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('remote_host', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guacamole_user_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserPasswordHistory',
            fields=[
                ('password_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=32)),
                ('password_salt', models.CharField(blank=True, max_length=32, null=True)),
                ('password_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'guacamole_user_password_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionAttribute',
            fields=[
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleconnection')),
                ('attribute_name', models.CharField(max_length=128)),
                ('attribute_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_connection_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionGroupAttribute',
            fields=[
                ('connection_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleconnectiongroup')),
                ('attribute_name', models.CharField(max_length=128)),
                ('attribute_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_connection_group_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionGroupPermission',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleentity')),
                ('permission', guacamole.fields.GuacamoleObjectPermissionTypeField(choices=[('READ', 'READ'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('ADMINISTER', 'ADMINISTER')], default='READ')),
            ],
            options={
                'db_table': 'guacamole_connection_group_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionParameter',
            fields=[
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleconnection')),
                ('parameter_name', models.CharField(max_length=128)),
                ('parameter_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_connection_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleConnectionPermission',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleentity')),
                ('permission', guacamole.fields.GuacamoleObjectPermissionTypeField(choices=[('READ', 'READ'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('ADMINISTER', 'ADMINISTER')], default='READ')),
            ],
            options={
                'db_table': 'guacamole_connection_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleSharingProfileAttribute',
            fields=[
                ('sharing_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamolesharingprofile')),
                ('attribute_name', models.CharField(max_length=128)),
                ('attribute_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_sharing_profile_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleSharingProfileParameter',
            fields=[
                ('sharing_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamolesharingprofile')),
                ('parameter_name', models.CharField(max_length=128)),
                ('parameter_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_sharing_profile_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleSharingProfilePermission',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleentity')),
                ('permission', guacamole.fields.GuacamoleObjectPermissionTypeField(choices=[('READ', 'READ'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('ADMINISTER', 'ADMINISTER')], default='READ')),
            ],
            options={
                'db_table': 'guacamole_sharing_profile_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleSystemPermission',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleentity')),
                ('permission', guacamole.fields.GuacamoleSystemPermissionTypeField(choices=[('CREATE_CONNECTION', 'CREATE_CONNECTION'), ('CREATE_CONNECTION_GROUP', 'CREATE_CONNECTION_GROUP'), ('CREATE_USER', 'CREATE_USER'), ('ADMINISTER', 'ADMINISTER')])),
            ],
            options={
                'db_table': 'guacamole_system_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserAttribute',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleuser')),
                ('attribute_name', models.CharField(max_length=128)),
                ('attribute_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_user_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserGroupAttribute',
            fields=[
                ('user_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleusergroup')),
                ('attribute_name', models.CharField(max_length=128)),
                ('attribute_value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'guacamole_user_group_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserGroupMember',
            fields=[
                ('user_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleusergroup')),
            ],
            options={
                'db_table': 'guacamole_user_group_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserGroupPermission',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleentity')),
                ('permission', guacamole.fields.GuacamoleObjectPermissionTypeField(choices=[('READ', 'READ'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('ADMINISTER', 'ADMINISTER')], default='READ')),
            ],
            options={
                'db_table': 'guacamole_user_group_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuacamoleUserPermission',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guacamole.guacamoleentity')),
                ('permission', guacamole.fields.GuacamoleObjectPermissionTypeField(choices=[('READ', 'READ'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('ADMINISTER', 'ADMINISTER')], default='READ')),
            ],
            options={
                'db_table': 'guacamole_user_permission',
                'managed': False,
            },
        ),
    ]
