# Generated by Django 3.2.7 on 2021-11-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_agreed_terms',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.IntegerField(default=0),
        ),
    ]
