# Generated by Django 3.2.4 on 2021-08-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0002_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuacamoleEntity',
        ),
        migrations.DeleteModel(
            name='GuacamoleUser',
        ),
    ]
