# Generated by Django 3.2.7 on 2021-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0004_make_aro_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chief_investigator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
