# Generated by Django 3.2.9 on 2021-12-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0006_add_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_workspace.project'),
        ),
    ]
