# Generated by Django 5.0.8 on 2025-01-09 05:30

import researcher_workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0008_user_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_agreed_terms',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=researcher_workspace.models.Char32UUIDField(
                blank=True, null=True, unique=True),
        ),
    ]
