# Generated by Django 3.2.7 on 2021-09-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher_workspace', '0003_auto_20210812_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('default_flavor_name', models.CharField(max_length=32)),
                ('big_flavor_name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='researcher_workspace.feature')),
            ],
        ),
    ]
