# Generated by Django 3.2.6 on 2021-09-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopType',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('image_name', models.CharField(max_length=256)),
                ('default_flavor_name', models.CharField(max_length=32)),
                ('big_flavor_name', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
