# Generated by Django 3.2.7 on 2021-09-15 07:04

from django.db import migrations

from django.conf import settings


class Migration(migrations.Migration):

    def addDesktopTypes(apps, schema_editor):
        DesktopType = apps.get_model('researcher_desktop', 'DesktopType')
        # Populate with sensible defaults from the settings.
        for desktop_type in settings.DESKTOP_TYPES:
            DesktopType.objects.create(**desktop_type)

    def removeDesktopTypes(apps, schema_editor):
        DesktopType = apps.get_model('researcher_desktop', 'DesktopType')
        DesktopType.objects.all().delete();

    dependencies = [
        ('researcher_desktop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addDesktopTypes, removeDesktopTypes)
    ]



