# Generated by Django 3.2.7 on 2021-10-20 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0002_bootstrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityZone',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('zone_weight', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='researcher_desktop.availabilityzone')),
            ],
        ),
        migrations.AddField(
            model_name='desktoptype',
            name='restrict_to_zones',
            field=models.ManyToManyField(to='researcher_desktop.AvailabilityZone'),
        ),
    ]
