# Generated by Django 3.2.12 on 2022-03-10 02:58

from django.db import migrations
from researcher_workspace.models import Char32UUIDField


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0002_bootstrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityzone',
            name='network_id',
            field=Char32UUIDField(null=True),
        ),
    ]
