# Generated by Django 3.2.25 on 2024-06-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0003_availabilityzone_network_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoptype',
            name='family',
            field=models.CharField(default='linux', help_text="Selects a cloud-config template;e.g. 'linux' or 'windows'", max_length=32),
        ),
        migrations.AlterField(
            model_name='desktoptype',
            name='volume_size',
            field=models.IntegerField(default=30, help_text='Size in GB'),
        ),
    ]
