# Generated by Django 5.0.8 on 2024-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0004_add_desktoptype_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoptype',
            name='launch_wait_extra',
            field=models.IntegerField(default=0,
                                      help_text='Extra launch wait time '
                                      'in seconds'),
        ),
    ]
