# Generated by Django 3.2.6 on 2021-11-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0004_populate_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoptype',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desktoptype',
            name='restrict_to_zones',
            field=models.ManyToManyField(blank=True, to='researcher_desktop.AvailabilityZone'),
        ),
    ]
