# Generated by Django 3.2.6 on 2021-11-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0005_add_json_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktoptype',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
