# Generated by Django 3.2.7 on 2021-11-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0006_alter_desktoptype_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktoptype',
            name='volume_size',
            field=models.IntegerField(default=20, help_text='Size in GB'),
        ),
    ]
