FACULTIES = {
    "ABP": 0,
    "ARTS": 0,
    "COO": 0,
    "EIT": 0,
    "FAM": 0,
    "FBE": 0,
    "MDHS": 0,
    "MGSE": 0,
    "MLS": 0,
    "SCI": 0,
    "US": 0,
    "VAS": 0,
    "RESEARCH - OTHER": 0,
    "OTHER": 0,
    "NOT_MAPPED": 0,
    "Total": 0,
}

FACULTY_MAPPING = {
    "Academic": "OTHER",
    "Academic Services and Registrar": "OTHER",
    "Accounting": "FBE",
    "Administration and Finance": "OTHER",
    "Advancement": "OTHER",
    "Agriculture and Food": "VAS",
    "Anatomy and Neuroscience": "MDHS",
    "Anatomy and Physiology": "MDHS",
    "Architecture, Building and Planning": "ABP",
    "Arts": "ARTS",
    "Asia Institute": "ARTS",
    "Asialink": "OTHER",
    "Atlantic Fellows for Social Equity": "OTHER",
    "Audiology and Speech Pathology": "MDHS",
    "Australia India Institute": "OTHER",
    "Australian Mathematical Sciences Institute": "SCI",
    "Australian National Academy of Music Ltd": "OTHER",
    "Baker Department of Cardiometabolic Health": "MDHS",
    "Bio21 Institute": "SCI",
    "Biochemistry and Molecular Biology": "SCI",
    "BioSciences": "SCI",
    "Biochemistry and Pharmacology": "MDHS",
    "Biomedical Engineering": "EIT",
    "Biomedical Research Victoria": "OTHER",
    "Business Administration": "FBE",
    "Business Intelligence and Reporting": "COO",
    "Business Services": "COO",
    "Business and Economics": "FBE",
    "CAVAL": "OTHER",
    "CERA Ltd": "MDHS",
    "Centre for Cancer Research": "MDHS",
    "Centre for Cultural Materials Conservation": "ARTS",
    "Centre for Digital Transformation of Health": "MDHS",
    "Centre for Youth Mental Health": "MDHS",
    "Centre for the Study of Higher Education": "MGSE",
    "Chemical Engineering": "EIT",
    "Chemical and Biomedical Engineering": "EIT",
    "Chemical and Biomolecular Engineering": "EIT",
    "Chemistry": "SCI",
    "Chief Financial Officer Group": "COO",
    "Chief Operating Officer": "COO",
    "Clinical Pathology": "MDHS",
    "Commercial Services": "US",
    "Computing and Information Systems": "EIT",
    "Critical Care": "MDHS",
    "Culture and Communication": "ARTS",
    "Digital and Data": "COO",
    "Doherty Institute": "MDHS",
    "Earth Sciences": "SCI",
    "Economics": "FBE",
    "Ecosystem and Forest Sciences": "SCI",
    "Electrical and Electronic Engineering": "EIT",
    "Electrical, Mechanical and Infrastructure Engineering": "EIT",
    "Engagement": "OTHER",
    "Engineering": "EIT",
    "Engineering and IT": "EIT",
    "External Relations": "US",
    "Finance": "FBE",
    "Fine Arts and Music": "FAM",
    "Florey Department of Neuroscience and Mental Health": "MDHS",
    "General Practice": "MDHS",
    "Geography": "SCI",
    "Graduate School of Business and Economics": "FBE",
    "Graduate School of Humanities and Social Sciences": "ARTS",
    "Graduate Student Association": "OTHER",
    "Grattan Institute": "OTHER",
    "Historical and Philosophical Studies": "ARTS",
    "Infectious Diseases": "MDHS",
    "Infrastructure Engineering": "EIT",
    "Intellectual Property Research Institute of Australia": "OTHER",
    "International": "OTHER",
    "International House": "OTHER",
    "Kendall Hall": "VAS",
    "Languages and Linguistics": "ARTS",
    "Law": "MLS",
    "Legal and Risk": "COO",
    "MHRI Department of Neuroscience in Mental Health": "MDHS",
    "MU Student Union Ltd": "OTHER",
    "Management and Marketing": "FBE",
    "Mathematics and Statistics": "SCI",
    "Mechanical Engineering": "EIT",
    "Medical Biology (W.E.H.I.)": "MDHS",
    "Medical Bionics Department": "MDHS",
    "Medical Education": "MDHS",
    "Medicine - Austin Health": "MDHS",
    "Medicine - Royal Melbourne Hospital": "MDHS",
    "Medicine - St Vincent's Hospital": "MDHS",
    "Medicine and Radiology": "MDHS",
    "Medicine, Dentistry and Health Sciences": "MDHS",
    "Medicine, Northern Health": "MDHS",
    "Medicine, Western Health": "MDHS",
    "Medley Hall": "OTHER",
    "Melbourne Business School": "FBE",
    "Melbourne Connect": "OTHER",
    "Melbourne Conservatorium of Music": "FAM",
    "Melbourne Dental School": "MDHS",
    "Melbourne Entrepreneurial Centre": "FBE",
    "Melbourne Graduate School of Education": "MGSE",
    "Melbourne Institute of Applied Economic and Social Research": "FBE",
    "Melbourne Medical School": "MDHS",
    "Melbourne School of Government": "MLS",
    "Melbourne School of Population and Global Health": "MDHS",
    "Melbourne School of Professional and Continuing Education": "FBE",
    "Melbourne School of Psychological Sciences": "MDHS",
    "Melbourne Theatre Company": "OTHER",
    "Melbourne University Publishing Ltd": "OTHER",
    "Melbourne University Sport": "OTHER",
    "Melbourne Veterinary School": "VAS",
    "Microbiology and Immunology": "MDHS",
    "Nossal Institute Ltd": "MDHS",
    "Nursing": "MDHS",
    "Obstetrics and Gynaecology Royal Women's Hospital/Mercy": "MDHS",
    "Operational Performance Group": "COO",
    "Ophthalmology Eye and Ear Hospital": "MDHS",
    "Optometry and Vision Sciences": "MDHS",
    "Otolaryngology": "MDHS",
    "Paediatrics Royal Children's Hospital": "MDHS",
    "Pharmacology and Therapeutics": "MDHS",
    "Physics": "SCI",
    "Physiology": "MDHS",
    "Physiotherapy": "MDHS",
    "Project Services": "COO",
    "Property": "COO",
    "Psychiatry": "MDHS",
    "Radiology": "MDHS",
    "Research": "RESEARCH - OTHER",
    "Research and Enterprise": "RESEARCH - OTHER",
    "Research, Innovation and Commercialisation": "COO",
    "Rural Health": "MDHS",
    "School of Biomedical Sciences": "MDHS",
    "School of Health Sciences": "MDHS",
    "Science": "SCI",
    "Social Work": "MDHS",
    "Social and Political Sciences": "ARTS",
    "Strategy and Culture": "OTHER",
    "Student Accommodation Unit": "COO",
    "Student and Scholarly Services": "COO",
    "Surgery": "MDHS",
    "Surgery - Austin Health": "MDHS",
    "Surgery - Royal Melbourne Hospital": "MDHS",
    "Surgery - St Vincent's Hospital": "MDHS",
    "Surgery, Northern Health": "MDHS",
    "Surgery, Western Health": "MDHS",
    "The Ian Potter Museum of Art": "OTHER",
    "The Sir Peter MacCallum Department of Oncology": "MDHS",
    "University House": "OTHER",
    "University Museums and Collections": "OTHER",
    "University Services": "US",
    "University of Melbourne Student Union": "OTHER",
    "UoM Commercial Ltd": "OTHER",
    "Veterinary Biosciences": "VAS",
    "Veterinary Clinical Sciences": "VAS",
    "Veterinary Hospital": "VAS",
    "Veterinary and Agricultural Sciences": "VAS",
    "Vice-Chancellor's Office": "OTHER",
    "Victorian College of the Arts": "FAM",
}
