# Generated by Django 3.2.4 on 2021-08-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guacamole', '0001_initial'),
        ('vm_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='guac_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guacamole.guacamoleconnection'),
        ),
    ]
