# Generated by Django 3.2.9 on 2021-11-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0002_add_availability_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmstatus',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmstatus',
            name='status_progress',
            field=models.IntegerField(default=0),
        ),
    ]
