# Generated by Django 3.2.7 on 2022-01-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0003_add_status_and_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudresource',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resize',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
