# Generated by Django 3.2.7 on 2022-02-02 07:03

from django.db import migrations, models

from researcher_workspace import models as workspace_models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0004_add_expires_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='rebooted',
            new_name='rebooted_at',
        ),
        migrations.AddField(
            model_name='volume',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='backup_id',
            field=workspace_models.Char32UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='shelved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
