# Generated by Django 3.2.7 on 2022-02-02 07:08

from datetime import datetime, timezone

from django.db import migrations


class Migration(migrations.Migration):

    def backfill_shelved_at(apps, schema_editor):
        Volume = apps.get_model("vm_manager", "Volume")
        for v in Volume.objects.all():
            if v.shelved and v.shelved_at is None:
                v.shelved_at = datetime.now(tz=timezone.utc)
                v.save()

    def backfill_shelved(apps, schema_editor):
        Volume = apps.get_model("vm_manager", "Volume")
        for v in Volume.objects.all():
            v.shelved = (v.shelved_at is not None)
            v.save()

    dependencies = [
        ('vm_manager', '0005_add_archiving_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_shelved_at,
                             reverse_code=backfill_shelved)
    ]
