# Generated by Django 3.2.7 on 2022-02-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0006_backfill_shelved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='shelved',
        ),
    ]
