# Generated by Django 3.2.7 on 2022-02-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0008_alter_cloudresource_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField()),
                ('stage', models.IntegerField(default=0)),
                ('stage_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResizeExpiration',
            fields=[
                ('expiration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vm_manager.expiration')),
            ],
            bases=('vm_manager.expiration',),
        ),
        migrations.CreateModel(
            name='ResourceExpiration',
            fields=[
                ('expiration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vm_manager.expiration')),
            ],
            bases=('vm_manager.expiration',),
        ),
        migrations.AddField(
            model_name='cloudresource',
            name='expiration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vm_manager.resourceexpiration'),
        ),
        migrations.AddField(
            model_name='resize',
            name='expiration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vm_manager.resizeexpiration'),
        ),
    ]
