# Generated by Django 3.2.7 on 2022-02-20 05:51

from datetime import datetime, timezone

from django.db import migrations


class Migration(migrations.Migration):

    def create_expiration_objects(apps, schema_editor):
        CloudResource = apps.get_model("vm_manager", "CloudResource")
        Resize = apps.get_model("vm_manager", "Resize")
        ResourceExpiration = apps.get_model(
            "vm_manager", "ResourceExpiration")
        ResizeExpiration = apps.get_model("vm_manager", "ResizeExpiration")
        now = datetime.now(timezone.utc)
        for r in CloudResource.objects.exclude(expires=None):
            e = ResourceExpiration(expires=r.expires, stage=0, stage_date=now)
            e.save()
            r.expiration = e
            r.save()
        for r in Resize.objects.exclude(expires=None):
            e = ResizeExpiration(expires=r.expires, stage=0, stage_date=now)
            e.save()
            r.expiration = e
            r.save()

    def repopulate_expiry_dates(apps, schema_editor):
        CloudResource = apps.get_model("vm_manager", "CloudResource")
        Resize = apps.get_model("vm_manager", "Resize")
        ResourceExpiration = apps.get_model("vm_manager", "ResourceExpiration")
        ResizeExpiration = apps.get_model("vm_manager", "ResizeExpiration")
        for r in CloudResource.objects.exclude(expiration=None):
            r.expires = r.expiration.expires
            r.save()
        for r in Resize.objects.exclude(expiration=None):
            r.expires = r.expiration.expires
            r.save()

    dependencies = [
        ('vm_manager', '0009_add_expiration'),
    ]

    operations = [
        migrations.RunPython(create_expiration_objects,
                             reverse_code=repopulate_expiry_dates)
    ]
