# Generated by Django 3.2.18 on 2023-07-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0015_backfill_backup_expiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudresource',
            name='expiration',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expiration_for',
                to='vm_manager.resourceexpiration'),
        ),
        migrations.AlterField(
            model_name='resize',
            name='expiration',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expiration_for',
                to='vm_manager.resizeexpiration'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='backup_expiration',
            field=models.OneToOneField(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expiration_for',
                to='vm_manager.backupexpiration'),
        ),
    ]
