#!/bin/bash

if [[ "$#" -ne 2 ]];
then
    >&2 echo "Illegal number of parameters: Need hostname, and current directory!"
    exit 255
fi

HN=$1

if [[ ! ${HN} =~ "cloud.unimelb.edu.au" ]];
then
  >&2 echo "Not a valid hostname!"
  exit 254
fi

echo "Removing $HN from puppet's tender care."
pemfile="$2/utils/pc.unimelb-instant-dashboard.cloud.edu.au.pem"
keyfile="$2/utils/pc.unimelb-instant-dashboard.cloud.edu.au.key"
curl --cert "$pemfile" \
--key "$keyfile" \
--cacert ca.pem \
-s \
-k -X DELETE -H 'Accept: pson' \
https://puppet.unimelb.edu.au:8140/puppet-ca/v1/certificate_status/"${HN}"?environment=production
